version: "3"
services:
  angular:
    build: frontend
    ports:
      - "4200:80"
    networks:
      - strapi-app-network

  strapiexample:
    image: strapi/strapi
    build: backend
    container_name: strapiexample
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: backend
      DATABASE_HOST: costestimatorbackend.ejnro.mongodb.net
      DATABASE_PORT: 27017
      DATABASE_USERNAME: pguttapalyam
      DATABASE_PASSWORD: Prav097
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    ports:
      - "1337:1337"

networks:
  strapi-app-network:
    driver: bridge
